### ISSUE TITLE
ZenHub Gantt Chart

### ISSUE THREAD

**Issue by Noah-Huppert** [Noah-Huppert/gh-gantt#9]
Provide a Gantt chart which provides additional issue information to users leveraging the ZenHub API.

**Comment by wolferlgo** [comment]
EEhm .. question...... is it possible to draw, create a GANTT CHart with ZEHNHUB ????  Never saw this

**Comment by Noah-Huppert** [comment]
@wolferlgo Hi, thanks for your interest in this project. May I ask you to clarify your question?

**Comment by Tovli** [comment]
@Noah-Huppert any plan to add a gantt chart to zenhub?

**Comment by Noah-Huppert** [comment]
@Tovli this project has been paused for the foreseeable future. All stakeholders involved no longer had a need for a gantt chart from ZenHub issues.

**Comment by Noah-Huppert** [comment]
I've added an update to the readme.
